version: "3.3"
services:
  app:
    image: avsimvadim/bookscatalogprototype
    container_name: bookscatalogprototype
    build: src/main/java/com/softserve/booksCatalogPrototype/docker
    ports:
      - "8080:8080"
    restart: always
    networks:
      - net-spring-db
    depends_on:
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: docker
  mongodb:
    image: library/mongo:4.2
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    networks:
      - net-spring-db
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - mynetwork
  jenkins:
    image: getintodevops/jenkins-withdocker:lts
    volumes:
      - jenkinsvolume:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    networks:
      - mynetwork

volumes:
  jenkinsvolume:
    external: true

networks:
  mynetwork:
  net-spring-db:
    driver: bridge











